version: '3.9'

services:
  database:
    image: postgres:16
    container_name: satta-app-db
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: "#29GGvu2oq"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - satta-app-db-volume:/var/lib/postgresql/data
    networks:
      - satta-app-net

  redis:
    image: redis:7-alpine
    container_name: satta-app-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - satta-app-redis-volume:/data
    networks:
      - satta-app-net

volumes:
  satta-app-db-volume:
  satta-app-redis-volume:


networks:
  satta-app-net:
    name: satta-app-net
