
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/basicNavbar";
import Header from "@/components/custom/basicHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trade On",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-stone-100">
          <div className="py-16 lg:px-80">{children}</div>
          <div className="fixed top-0 w-full bg-white shadow z-50 lg:px-80">
            <Header/>
          </div>
          <div className="fixed bottom-0 w-full bg-white shadow z-50 lg:px-120">
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
